# Generated by Django 5.2.17 on 2026-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
